### ISSUE TITLE
Follow and consider if mega-linter could be a working/safe alternative to super-linter

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#147]
https://nvuillam.github.io/mega-linter/
https://nvuillam.github.io/mega-linter/#mega-linter-vs-super-linter

> Mega-Linter can automatically apply fixes performed by linters, and push them to the same branch, or create a Pull Request that you can validate
> This is pretty handy, especially for linter errors related to formatting (in that case, you don’t have any manual update to perform)

**Comment by nvuillam** [comment]
I'm here to help if you have any question :)
