### ISSUE TITLE
Broken link in the k8s tutorial with EC3

### ISSUE THREAD

**Issue by sebastian-luna-valero** [EGI-Federation/documentation#231]
# Short Description of the issue

I am reading through the k8s docs: https://docs.egi.eu/users/cloud-container-compute/k8s/

There are broken links to the "EC3 tutorial" with URL: https://docs.egi.eu/users/cloud-container-compute/cloud-compute/ec3

Should these point to https://docs.egi.eu/users/cloud-compute/ec3/ instead?

# Summary of proposed changes

If the answer is yes, I am happy to open a PR to fix it.

**Comment by enolfc** [comment]
The anwser is Yes 😉
