### ISSUE TITLE
Same content to run tests locally

### ISSUE THREAD

**Issue by sebastian-luna-valero** [EGI-Federation/documentation#237]
# Short Description of the issue

There are two ways to set up local tests for this repository:
* https://docs.egi.eu/about/contributing/git/#running-the-site-locally
* https://github.com/EGI-Federation/documentation#installing-dependencies-building-and-testing-locally

# Summary of proposed changes

Would it be possible for both sections to contain the same information?

Specifically, I would like to:
* Leave https://github.com/EGI-Federation/documentation#installing-dependencies-building-and-testing-locally as it is
* Update https://docs.egi.eu/about/contributing/git/#running-the-site-locally with the content in https://github.com/EGI-Federation/documentation#installing-dependencies-building-and-testing-locally

Moreover, I think we should include:
```
npm install -g markdownlint-cli
```

To be able to reproduce `Super-Linter` tests locally.

If you agree, I am happy to submit a PR with the proposed changes.

Best regards,
Sebastian

**Comment by gwarf** [comment]
Hi @sebastian-luna-valero , for sure the install doc should be harmonised and promote using `npm ci`.
But please don't inlcude documentation asking to install npm packages globally, I don't think we want to promote doing this.
I've never tried to run Super-Linter locally, and been relying on individual linters setup locally in my text editor.

Feel free to create any PR for harmonising/improving this.
