### ISSUE TITLE
Font size too small after theme update

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/documentation#249]
# Short Description of the issue

Font size too small

**Comment by gwarf** [comment]
Closing this task (for the record at 125 % zoom level it's comfortable for me).

**Comment by gwarf** [comment]
So in fact it seems I didn't closed it, but in fact I still have the issue.
As an example if I open https://www.docsy.dev/docs/adding-content/navigation/ with the default zoom level all is fine, while for me https://docs.egi.eu is still a bit too small.
