### ISSUE TITLE
Discuss, document and enforce style rules for code excerpts

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#271]
As discussed in https://github.com/EGI-Federation/documentation/pull/270#discussion_r685898238 we need to have clear requirements/guidelines on how to present code excerpts, clarifying how a prompt sign should be shown and long command lines handled.

As an example we could agree to break long commands (but not their output) so that they can be directly seen without having to scroll horizontally and always add a prompt indicator (just `$`?) to easily make the distinction between a command and its output. 
Output should also probably only be included when it adds something.

@enolfc, @andrea-manzi, @thebe14 (and others), thoughts/opinions?

Markdownlint rule: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014
Rationale for the rule: https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code

If the rule is to be disabled it should be added to https://github.com/EGI-Federation/documentation/blob/main/.github/linters/.markdownlint.json. The style guide would also have to be updated.

**Comment by thebe14** [comment]
There are two things to decide here:

A whether we should use linter rule [commands-show-output](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output) and
B whether or not we should break long command lines.

---------------------

I disagree with rule A, as it is inconsistent. it accepts a prompt in front of a command only if the shell excerpt also shows command output, but it flags an error if the shell block only shows the command (one line, so no command output). consistency is much more important than making an opinionated linter happy.

We either put the prompt in all shell examples or we don't put it in any of them. 

Some examples from commercial documentation: [AWS docs always show the prompt](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-lamp-amazon-linux-2.html), [Linode docs never show the prompt](https://www.linode.com/docs/guides/deploy-and-manage-lke-cluster-with-api-a-tutorial/) but also never show any command output.

Considering we have examples with just the command but also with the command + command output, I would chose to put the prompt everywhere (disable this rule). 

--------------------

I also disagree with B. Shell commands are not code. If we break them using backslashes just for readability or narrow browser windows/small screens, that means those lines will stay broken, irrespective of how the browser is resized. No commercial documentation does this. 

Some examples (try resizing the pages below until the content becomes a narrow column -> you will see that the shell examples get a horizontal scroll bar):
[AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-lamp-amazon-linux-2.html)
[Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-cli)

What we need is a recommendation to make the examples as simple as possible, commands as short as possible. E.g. prepare everything via environment variables, so the commands can be as brief as possible. But do not break commands in the docs, and definitely do not break command output, that would be seriously confusing.

**Comment by gwarf** [comment]
Regarding A, I personally tend to agree to https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014
and https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code (ie. remove useless noise when not needed) but I'm not concerned enough about this to discuss this endlessly. Let's see what some colleagues will prefer.

Also if we enforce having a prompt/`$` sign where there is no output it would be nice to have the copy button not copy the prompt info, like done on [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-lamp-amazon-linux-2.html).

For B, there was no discussion about breaking output (I explicitly mentioned this), only commands, like done on the commercial linode docs you mentioned and that is nicely breaking long lines making them easier to read, and also showing more cleanly what are the different arguments.

![Screenshot 2021-08-11 at 14 51 52](https://user-images.githubusercontent.com/451417/129031808-c0c5cafd-6e6e-4fb4-a51a-177ccd36001d.png)

For me having to horizontally scroll to see a command is just a pain and an anti-feature. Those documentation pages are usually not read full screen as people will want to use a terminal at the same time to do things (like having them side by side).

Let's see what others prefer.

Another point: I see that [Lineode](https://www.linode.com/docs/guides/deploy-and-manage-lke-cluster-with-api-a-tutorial#create-an-lke-cluster) is also separating the commands from their output, like this:

![Screenshot 2021-08-11 at 14 55 03](https://user-images.githubusercontent.com/451417/129032253-11d92d33-9e35-43a4-aea7-25a12cf4a647.png)

[DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04) is also doing the same:

![Screenshot 2021-08-11 at 14 55 53](https://user-images.githubusercontent.com/451417/129032385-895f5abd-d861-4386-a918-b2fd7d9ebd7d.png)

It ease making the distinction between input/output and would allow to always copy commands using the copy button.

**Comment by sebastian-luna-valero** [comment]
Hi,

I vote for separating commands from output, and removing the `$` sign to make use of a the copy button. I also vote for using backslashes appropriately to improve readability of long command lines.

Best regards,
Sebastian

**Comment by thebe14** [comment]
> Also if we enforce having a prompt/$ sign where there is no output it would be nice to have the copy button not copy the prompt info, like done on AWS docs.

I can try to implement this

**Comment by thebe14** [comment]
Digital Ocean separates the command from output, yet still show the prompt in the command.

**Comment by gwarf** [comment]
Yes, everyone is doing how they fill it's better...

With the updated copy option you implemented allowing to copy all commands, I'm less against the usage of `$`, and having `$` as prompt helps differentiate what is a command and what is an output, so maybe making less required/interesting to move output to a dedicated code block.

Let's wait for more feedback.

**Comment by crsndr** [comment]
I think separating command from output might indeed help with copy and paste, If you separate them and the text clearly says use this command which should produce this output then I think would be clear even without the $ sign. I'm not sure about trying to keep the length of the commands limited. It could make it more readable in some circumstances however depending on the screen size or window size you might need to scroll anyway even if you tried to have relatively short lines.

**Comment by thebe14** [comment]
Andrea, the copy-paste argument you are using is moot. Improvements to the Copy button in shell examples were implemented that copy just the command(s), even when broken to multiple lines, and the command output is never copied. Try it out on the live documentation site. E.g. here https://docs.egi.eu/users/online-storage/block-storage/#list-volumes

**Comment by crsndr** [comment]
@thebe14 Indeed it works well, it copy just the command and you can paste it directly. It works perfectly well. Still I have a small preference in keeping it separated as it might be more clear to me. It's only a preference. In your examples works well anyway.

**Comment by thebe14** [comment]
Rules changes as agreed in #272
