### ISSUE TITLE
Take a final decision on line length

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#272]
The line length limit can be problematic in some cases, having people to add exceptions and also making it more difficult for people sending updates using the GitHub web interface.
We could decide to remove this requirement (updating prettier configuration using https://prettier.io/docs/en/options.html#prose-wrap and adjusting the linter used in GitHub actions).

@enolfc, @andrea-manzi, @thebe14 and others: thoughts/opinions?

**Comment by thebe14** [comment]
The main reasoning for rule [line-length](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length) is that people are also editing the source of files in terminals or small editors and unlimited lines are definitely not handy/clean.

This is not a valid argument, in my opinion. Absolutely all text editors can toggle line wrap, including the ancient vi. Letting the author organize text as he/she best can work with it trumps all arguments for rules about how the source should be formatted. **What you really care about is content. Make that easy to produce, have the rendered output look great. Everything else is secondary.**

E.g. I gave up on prettier, it messes up the formatting in some cases. but more importantly, it makes reading the docs in a text editor a pain (after it applies rigorous follow-the-rules formatting). So to be able to organize my thoughts, I prefer editing the source files manually, and keep source text human readable so I can easily scan it and write/correct/improve it.

I would keep prettier as a recommendation for occasional contributors, but I would not enforce the line length (and other similar source-esthetic rules).

**Comment by thebe14** [comment]
Other rules that should not be enforced, in my opinion (but the prettier configuration we offer as a recommendation should format respecting these rules):

[line-length](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length)
[trailing-spaces](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md009---trailing-spaces)
[no-multiple-blanks](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md012---multiple-consecutive-blank-lines)
[single-trailing-newline](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md047---file-should-end-with-a-single-newline-character)

**Comment by gwarf** [comment]
I personally wouldn't agree with disabling trailing-spaces, no-multiple-blanks and single-trailing-newline, I don't really see any good reason to disable those checks.

If there is a consensus on enforcing a line length, looking at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length it seems we could also easily disable long lines check for tables and code blocks, it would already remove most of the exception people had to add.

Let's wait for colleagues' feedback.

**Comment by sebastian-luna-valero** [comment]
Hi,

I am happy with keeping the line length limit as is since it improves readability, specially when you just want to look at the raw code on GitHub using the web browser.

Sebastian.

**Comment by crsndr** [comment]
Except for the line-length I would keep the other checks as they might avoid some undesired formatting, like having multiple spaces between words which are usually quite hard to spot.
Indeed as Sebastian says it might be less readable without line-length if you read directly on GitHub. How common is this case?

**Comment by thebe14** [comment]
For reading on the GitHub website I think a recommendation about line length is enough. Recommendation = include this rule in the prettier ready-to-use settings file we offer/recommend. Most of the contributors will take this settings file, use it, end of story.

The rules under discussion are the ones I listed above. The others are good to have (e.g. the one about exactly one space between words). But tell me, what is the value of enforcing that there is no space at end of lines? It renders the same with or without. Sure, a recommendation is welcome. But to fail a PR check for it? Why?

**What we really care about is content. Make that easy to produce, have the rendered output look great. Everything else is secondary.**

**Comment by gwarf** [comment]
Some flavour of markdown are using spaces at the end of line to trigger line breaks, but it's not very/clean convenient to rely on usually non visible character.
Ensuring that all the source is using a coherent and common style, and having this style enforced by checks on PR is to ensure the source stays clean. It also push to people the habits of not adding useless characters (spaces, new lines,...) when the write doc or code.

As said we also decided to go with prettier to avoid having to discuss again and again every style rules and loose time as everyone can be very opinionated about this and as you said, it's not what matters the most.

I'm currently quite fine with the proposition in https://github.com/EGI-Federation/documentation/pull/278#issuecomment-898485320:

* keep commands and output in the same block
* add prompts for all commands (this implies disabling the linter rule commands-no-output)
* break long commands to multiple lines

**Comment by enolfc** [comment]
Personally, I would keep all the rules :) Even if I tend to fail to format things properly most times, I prefer keeping consistency across all files. With my ancient editor (vi) moving around with long lines is not very comfortable, but I can live with it, so I don't mind having longer lines if needed. Still I would keep code blocks limited to around 80 chars (which I understand is not easy to enforce automatically, but we can try to detect bad situations during PRs).

As we are actually using prettier, can we add some sort of hook that reformats code before committing (or pushing) so people does not have to worry about that? This would also avoid people getting confused when going through the web interface of GitHub.

**Comment by thebe14** [comment]
@enolfc the line length in code/shell examples is discussed in #271 and I (finally) agree that commands should be broken to multiple lines (around 80 cars or even less). 

the problem I have with prettier (and other auto-formatting tools) is that they are stupid. they sometimes fail. and even when they do not fail, machine formatted content is very hard (for me) to read, organize, and improve while creating content. so I prefer to write manually, which means I am doing minor violations of these rules (the most I fail at is forget a space at the end of a line, or go over the line length by 1-2-3 chars). I just do not see the value in enforcing these. 

sure, provide prettier settings that will format according to these. that will ensure most of the contributors (especially ones that rarely contribute) will produce content that respect those rules. but if there are 10 spaces we could trim from a page, is that valuable to do? if the rendered content is the same? I wasted 15+% of my time constantly correcting these.

**Comment by gwarf** [comment]
The point of prettier is also to avoid having to format manually, thus removing some of the pains your are encountering by skipping it.

While I agree automated formatting may not be perfect and sometimes too strict, currently I think it's an acceptable drawback of having everything easily formatted in a common way following clear and shared guidelines.

I don't have in mind a specific problem with prettier that was a complete failure or that wasn't solved with some simple change or workaround, but if there are recurrent/known problems we can see how to address them and/or document them (at least).
I also do not feel that prettier-formated content is `really hard` to read and organise, for me it's more the opposite in fact (as an example text with long lines is harder to read).
The main thing that I feel is a bit of a pain to read are wide tables, but it's more a generic problem due to how markdown formats them than to prettier. 

We could indeed look at introducing and testing a GitHub action to auto-format code, it would certainly be very useful for web contributions and maybe also for new/less technical/in a hurry users.

**Comment by gwarf** [comment]
And yes, feedback is always valuable :)

**Comment by enolfc** [comment]
I agree with @gwarf above. 
Besides the line length limitation, which can be a bit painful to deal with, other formatting is normally quite ok and hasn't prevented me from being able to organise docs as needed. I don't think it's just a matter of trimming 10 spaces but keeping things consistent and making it easier for everyone to contribute, which if we can just  

So why don't we remove the line-length limit, still recommend something around 80 chars, and keep the other rules and work to have them automated?

**Comment by thebe14** [comment]
OK, then let's wrap up these two discussions and finally merge PR #278

**Comment by gwarf** [comment]
I'm fine with this summary.

**Comment by thebe14** [comment]
Rules changed as agreed above
