### ISSUE TITLE
The provided hugo binary is no more used to build the site

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#281]
The provided hugo binary is no more used to build the site: when moving from Travis to GitHub actions an action allowing to install a specific hugo version dynamically and making useless to store the binary in the project directory.

If we want to keep using an embed version (to save time in workflows) we need to update the workflows.
Otherwise it probably makes sense to drop the binaries directory and adjust installation notes, unless we fill that providing the binaries is useful for people willing to build/test the repository locally (making it easier).

Opinions?

**Comment by gwarf** [comment]
It also means that the site is still built using Hugo 0.66.0 as documented in https://github.com/EGI-Federation/documentation/blob/9f716ffb3427f448a05451229f8874c0bbca2280/.github/workflows/deploy.yml#L28.

**Comment by thebe14** [comment]
I installed Hugo locally, not using the binaries in the repo.

**Comment by gwarf** [comment]
Is it easy to do this on Windows? Or is it needed to do painful things like editing the PATH?
For Linux and macOS it will be straightforward, so if it's also simple on Windows we can drop it.

**Comment by enolfc** [comment]
Dropping makes sense. It would be nice in any case having #173 to just remove the need to have things locally installed for those contributors without so much experience

**Comment by martaguti** [comment]
I installed Hugo myself (macOS) as it was listed in the requirements. 
By the time I realised it is also provided with the repo, it was too late :-)

**Comment by gwarf** [comment]
So #288 will drop it, so it won't have been useless to install it manually ;)
