### ISSUE TITLE
Preview of PRs does not include draft pages

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/documentation#321]
The previews should also build and run so that draft pages are visible. Otherwise these previews do not make much sense for content that is added to draft pages (e.g. PR #319). Or maybe there should be no PRs for still-draft content?

# Summary of proposed changes

**Comment by gwarf** [comment]
I don't see much reason to have PR with drafts (apart maybe for having some templates/or placeholders to be used later), people can make tests in their own repo, for me PR are more for including ready to be displayed content.
I think that in #319 the draft option should be removed (mentioned in the comments).

**Comment by gwarf** [comment]
the preview is really meant to see how the final site will look like before deploying  it for real.

**Comment by thebe14** [comment]
@crsndr closing this
