### ISSUE TITLE
Add IM/EC3 documentation

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/documentation#38]
# Short Description of the issue

We need some documentation on how IM and/or EC3 are used within fedcloud.

**Comment by gwarf** [comment]
IM is covered in https://docs.egi.eu/users/cloud-compute/im/ and EC3 is covered in https://docs.egi.eu/users/cloud-compute/ec3/.
Can we close this task @enolfc ?

**Comment by enolfc** [comment]
Done in #242
