### ISSUE TITLE
Update documentation structure

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/documentation#411]
The documentation needs some changes to the structure, in order to accommodate new services and to make it easier to navigate. A lot of (most) content from the EGI-ACE [D2.3](https://docs.google.com/document/d/1ycq076_SQ6pIH3MabruDpCviIERWVQ_l/edit#) and [D2.5](https://docs.google.com/document/d/1ycq076_SQ6pIH3MabruDpCviIERWVQ_l/edit#) should end up in our documentation. The proposed structure is:

```
Getting Started
|-...

Tutorials
|-Create your very first VM
|-...
|-Classify images using ML

Authentication & Authorization
|-Check-in

Compute
|-Cloud Compute
     |-Images
     |-Networking
     |-Security
     |-GPUs
     |-Dynamic DNS
     |-Automating Deployments
     |-Monitoring & Management
|-Cloud Container Compute
|-High Throughput Compute
|-High Performance Compute
|-Software Distribution
|-Orchestration
     |-Infrastructure Manager
     |-Cloud Compute Clusters
     |-PaaS Orchestrator
     |-Dynamic On-Demand Analysis Software
     |-Workload Manager

Data
|-Storage
     |-Block Storage
     |-Object Storage
     |-Grid Storage
|-Data Management
     |-DataHub
     |-Data Transfer
     |-Rucio

Security
|-Secrets Store

Machine Learning
|-?

Development Environments
|-Notebooks
|-Binder

Training
|-Infrastructure
|-Webinars
|-YouTube
```

**Comment by thebe14** [comment]
An idea would be to move "Orchestration" under "Compute", and "Data Management" under "Storage". 
Pros? Cons?
@enolfc @andrea-manzi @gwarf

**Comment by enolfc** [comment]
El mié., 16 feb. 2022 12:47, Levente Farkas ***@***.***>
escribió:

> An idea would be to move "Orchestration" under "Compute", and "Data
> Management" under "Storage".
> Pros? Cons?
> @enolfc <https://github.com/enolfc> @andrea-manzi
> <https://github.com/andrea-manzi> @gwarf <https://github.com/gwarf>
>

For compute I could see that working, but for storage I see more "Data" as
parent.
We still miss DynDNS and CVMFS to be included somewhere (compute?, Helper
services?)

**Comment by thebe14** [comment]
Yes, what we have today under Cloud Compute remains there (and includes a page "Images" that covers AppDB (and could also cover CVMFS). I just did not add them above, as the tree is already too big.

**Comment by gwarf** [comment]
Yes I see also Data and Compute as the two main aspects.
CVMFS is Content Distribution, and it may fall logically under Data, while I see it also mainly relevant to compute.
Would we have potential other "Helper services"?

**Comment by thebe14** [comment]
So you are both in favor of tucking Orchestration under Compute and Storage under Data? Or keep all 4 of them as separate nodes in the root?

**Comment by thebe14** [comment]
> Would we have potential other "Helper services"?

What do you see will fit there (better than anywhere else in the above structure)?

**Comment by gwarf** [comment]
I see you moved Orchestration under Compute and Storage under Data, it's fine with me.

**Comment by gwarf** [comment]
> > Would we have potential other "Helper services"?
> 
> What do you see will fit there (better than anywhere else in the above structure)?

Enol suggested this for DynDNS and Content Distribution. But I feel we could start by keeping them under Compute. (if we agree that Content Distribution makes more sense under compute than under data, as it's mainly to distribute software to be used for compute). With the evolution of Content Distribution we can later see (as it's currently a bit blurry to me) if it's worth to move it elsewhere like under Data or some "Helper services" category.

**Comment by enolfc** [comment]
I see CVMFS halfway between data and compute: it's content distribution but it's for distributing software mainly, not a general purpose data service. My preference would be to keep it under Compute if need to pick one. DynamicDNS probably too, so for simplicity let's put it there

**Comment by thebe14** [comment]
It is already there.

**Comment by enolfc** [comment]
> Do you think we should keep the page "Images" just for AppDB and add another one like "Software" for CVMFS?

CVMFS is usable from Cloud, HTC and potentially HPC, I would move it under Compute directly

>> DynamicDNS probably too [under Compute]

> It is already there.

I don't see it 🤷

**Comment by thebe14** [comment]
You are right, I meant it is already there under the current docs. Added it in the OP too.

**Comment by enolfc** [comment]
Proposed org LGTM

**Comment by gwarf** [comment]
Looks good to me, but I would suggest to potentially sort alphabetically the sub entries like under Cloud Compute and others. I feel the ordering is currently quite arbitrary, and may be difficult to respect.
Also OK if you thinks it's more appropriate to keep it sorted like it is.
