### ISSUE TITLE
Error page for documentation

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/documentation#419]
Implement an error page that has a nicely worded intro to the docs and links to the user and provider docs top pages.

This should be possible, according to https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by gwarf** [comment]
See also https://gohugo.io/templates/404/

**Comment by gwarf** [comment]
Implemented.
