### ISSUE TITLE
Add redirects from the old documentation sections

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/documentation#420]
Create HTML pages in each (top) folder of the old documentation structure, that will redirect to the new documentation pages. These do not show up in the documentation left-side navigation bar, and we can keep them (at least for a while) as a safety net.

**Comment by gwarf** [comment]
Reltaed to #414

**Comment by NicolasLiampotis** [comment]
We would like an HTML page for the Check-in end-user documentation which has moved from https://docs.egi.eu/users/check-in/ to https://docs.egi.eu/users/aai/check-in/

**Comment by gwarf** [comment]
We expect #423 fixed the errors, please let us know if it's not the case or if some URL is missing a redirection.
