### ISSUE TITLE
Location of pages for Workload Manager

### ISSUE THREAD

**Issue by sebastian-luna-valero** [EGI-Federation/documentation#439]
# Short Description of the issue

Currently `Workload Manager` is placed under `Cloud Orchestration`:

https://docs.egi.eu/users/compute/orchestration/workload-manager/

Is it correct?

# Summary of proposed changes

Perhaps `Workload Manager` should be placed under `High Throughput Compute` Instead?

https://docs.egi.eu/users/compute/high-throughput-compute/

**Comment by gwarf** [comment]
@enolfc, what's your opinion on this?

**Comment by enolfc** [comment]
I think it's not correctly placed now, but putting it under HTC is not good either.
A possible solution would be to rename "Cloud Orchestration" to "Orchestration" and have a better Overview that is more inclusive for Workload Manager (good thing is that this does not change anything in the URLs as it's already `orchestration`)

**Comment by gwarf** [comment]
I also feel that renaming to Orchestration seems appropriate, and not touching the URL sounds great.

**Comment by gwarf** [comment]
I think we can now close this.
