### ISSUE TITLE
providers/check-in/idp/ is pointing to a page in wiki.egi.eu for integration with ELIXIR AAI

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#489]
In https://docs.egi.eu/providers/check-in/idp/#integration-success-stories there is a link to https://wiki.egi.eu/wiki/EGI_AAI_integration_with_ELIXIR_AAI.
As the wiki.egi.eu is being decommissioned, the link should be urgently removed or replaced.
And if this content should be kept it should be moved somewhere else.

**Comment by nikosev** [comment]
Hello @gwarf ,
It is safe to remove this, ELIXIR AAI is being decommissioned.
As I can see, there are many links in our documentation that link to wiki.egi.eu.
I will push a PR, replacing all deprecated links.

**Comment by gwarf** [comment]
I've also taken care of some links in #488 that is still being worked on.

**Comment by gwarf** [comment]
Implemented.
