### ISSUE TITLE
Document (like a FAQ) how a user could find back all the VMs he started

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#496]
It would be helpful to provide guidance on how a user could retrieve information on all the VM he started.
Sometimes people forgot where they started a VM, didn't logged their ID or else.

Apparently it may be done via:
* `fedcloud openstack server list --site ALL_SITES --vo <VO>`: this will list all VMs of the VO, not only the one belonging to the user, so some filtering will have to be done
* `list-all-my-own-vms.sh`, from fedcloudclient, cf https://fedcloudclient.fedcloud.eu/cheat.html#useful-commands. This is taking care of filtering the VM

**Comment by sebastian-luna-valero** [comment]
Hi,

Should it be added to the existing FAQ for Cloud Compute? https://github.com/EGI-Federation/documentation/pull/497

**Comment by gwarf** [comment]
Yes, I think so, thanks for looking into this!

**Comment by sebastian-luna-valero** [comment]
Great, solved in https://github.com/EGI-Federation/documentation/pull/497
