### ISSUE TITLE
Update GPU information for IISAS-FedCloud site

### ISSUE THREAD

**Issue by astalosj** [EGI-Federation/documentation#581]
# Short Description of the issue

IISAS-FedCloud site added 7 NVIDIA A100 40GB GPUs accessible to icecube and vo.beamide.com VOs.

# Summary of proposed changes

| Site | VM configuration options | Flavors | Supported VOs with GPUs | Access conditions | More information |
| ---- | ------------------------ | ------- | ----------------------- | ----------------- | ---------------- |
| IISAS-FedCloud | up to 7 NVIDIA A100 40GB, up to 8 NVIDIA Tesla K20m | g1.c08r30-K20m, g1.c16r60-2xK20m, A100 GPUs accessible using private flavors | vo.access.egi.eu, training.egi.eu, eosc-synergy.eu, vo.ai4eosc.eu, icecube, vo.beamide.com | Sponsored, conditions to be negotiated | |

**Comment by gwarf** [comment]
Hi @astalosj, would you be able to open a PR?
You can do it online using the "edit this page" button at the top right of https://docs.egi.eu/users/compute/cloud-compute/gpgpu/ , or using the usual fork/clone/PR GitHub flow.

**Comment by astalosj** [comment]
Done: https://github.com/EGI-Federation/documentation/pull/582
