### ISSUE TITLE
Secrets Store Web Interface - link to origin in documentation

### ISSUE THREAD

**Issue by brucellino** [EGI-Federation/documentation#656]
# Short Description of the issue

On the page, there is a direct link to what seems to be the service's origin 

`https://vault.services.fedcloud.eu:8200/`

Should this be

`https://secrets.egi.eu` ?

# Summary of proposed changes

Change `https://vault.services.fedcloud.eu:8200/` to `https://secrets.egi.eu`

**Comment by sebastian-luna-valero** [comment]
Thanks!

Should we also update the other references? See https://github.com/EGI-Federation/documentation/pull/657
