### ISSUE TITLE
Backup options for cloud compute

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/documentation#91]
# Short Description of the issue

We should have some documentation on how to perform backups in cloud compute service

# Summary of proposed changes

**Comment by enolfc** [comment]
Coming from https://github.com/EGI-Foundation/fedcloud-documentation/issues/17

**Comment by thebe14** [comment]
I added a description of how to backup bock storage in PR #270, see here https://docs.egi.eu/users/online-storage/block-storage/#backup-a-volume

**Comment by gwarf** [comment]
@enolfc, can we mark this issue as completed?

**Comment by enolfc** [comment]
Let's close this.
It is a bit undefined what's the OLA/SLA behind these backups though. It may be needed to clarify what is guaranteed or what not
